<a href="https://colab.research.google.com/github/Osakana7777777/GaussianProcessAndML/blob/main/ch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#準備

In [10]:
import numpy as np

#1.4 リッジ回帰


リッジ回帰の解（公式1.6）

$w=(\mathbf{X}^{T}\mathbf{X}+\alpha\mathbf{I})^{-1}\mathbf{X}^{T}\mathbf{y}$


In [6]:
X1=np.array([
    [1,2,4],
    [1,3,6],
    [1,4,8]
])
X2=np.array([
    [1,2,4],
    [1,3,6.1],
    [1,4,7.9]
])

In [11]:
print(np.dot(X1.T,X1)) #(1.70)
print(np.linalg.inv(np.dot(X2.T,X2))) #(1.72) wの絶対値が大きくなってしまう 

[[  3   9  18]
 [  9  29  58]
 [ 18  58 116]]
[[   6.33333333   18.          -10.        ]
 [  18.          254.         -130.        ]
 [ -10.         -130.           66.66666667]]


In [13]:
#Ridge regression
def ridge(X,y,alpha):
  tmp1=np.linalg.inv(np.dot(X.T,X)+alpha*np.eye(X.shape[0]))
  tmp2=np.dot(tmp1,X.T)
  w=np.dot(tmp2,y)
  return w

#例7
y=np.array([1,2,3])
print(ridge(X1,y,alpha=0.1)) #(1.79)

[-0.65610355  0.17853158  0.35706316]


リッジ回帰は正則化の一種（L2正則化）である．パラメータの絶対値を大きくしないようにして過学習を抑制する．L1正則化であるLasso回帰は，特徴量の多くを0にする効果（スパース性）があり，特徴量選択に用いることができる．