<a href="https://colab.research.google.com/github/Osakana7777777/GaussianProcessAndML/blob/main/ch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#準備

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#1.4 リッジ回帰


リッジ回帰の解（公式1.6）

$w=(\mathbf{X}^{T}\mathbf{X}+\alpha\mathbf{I})^{-1}\mathbf{X}^{T}\mathbf{y}$


In [6]:
X1=np.array([
    [1,2,4],
    [1,3,6],
    [1,4,8]
])
X2=np.array([
    [1,2,4],
    [1,3,6.1],
    [1,4,7.9]
])

In [11]:
print(np.dot(X1.T,X1)) #(1.70)
print(np.linalg.inv(np.dot(X2.T,X2))) #(1.72) wの絶対値が大きくなってしまう 

[[  3   9  18]
 [  9  29  58]
 [ 18  58 116]]
[[   6.33333333   18.          -10.        ]
 [  18.          254.         -130.        ]
 [ -10.         -130.           66.66666667]]


In [13]:
#Ridge regression
def ridge(X,y,alpha):
  tmp1=np.linalg.inv(np.dot(X.T,X)+alpha*np.eye(X.shape[0]))
  tmp2=np.dot(tmp1,X.T)
  w=np.dot(tmp2,y)
  return w

#例7
y=np.array([1,2,3])
print(ridge(X1,y,alpha=0.1)) #(1.79)

[-0.65610355  0.17853158  0.35706316]


リッジ回帰は正則化の一種（L2正則化）である．パラメータの絶対値を大きくしないようにして過学習を抑制する．L1正則化であるLasso回帰は，特徴量の多くを0にする効果（スパース性）があり，特徴量選択に用いることができる．

#scikit-learnで線形回帰実装

In [50]:
import sklearn
from sklearn.linear_model import LinearRegression,Ridge,Lasso
np.random.seed(0)

#dataset
from sklearn.datasets import load_diabetes
df=load_diabetes(return_X_y=True,as_frame=True)
X,y=df[0],df[1]
X

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [28]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [29]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB


In [63]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)



reg_linear=LinearRegression()
reg_linear.fit(X_train,y_train)
y_pred=reg_linear.predict(X_test)
loss=mean_squared_error(y_test,y_pred)
r2=reg_linear.score(X_test,y_test)
print(f"loss:{loss},R2:{r2}")

print(f"coefficients:{reg_linear.coef_}")

loss:3488.139059897988,R2:0.4050829718566291
coefficients:[ -25.43244717 -271.30474646  547.37842435  338.03366263 -711.78960153
  412.6215777    59.51915854  203.75265702  719.71729374   25.55346136]


In [62]:
#ridge regression
reg_ridge=Ridge()
reg_ridge.fit(X_train,y_train)
y_pred=reg_ridge.predict(X_test)
loss=mean_squared_error(y_test,y_pred)
r2=reg_ridge.score(X_test,y_test)
print(f"loss:{loss},R2:{r2}")

print(f"coefficients:{reg_ridge.coef_}")

loss:3379.4063076042653,R2:0.3409800318493462
coefficients:[  21.34794489  -72.97401935  301.36593604  177.49036347    2.82093648
  -35.27784862 -155.52090285  118.33395129  257.37783937  102.22540041]


In [61]:
#ridge regression
reg_lasso=Lasso()
reg_lasso.fit(X_train,y_train)
y_pred=reg_lasso.predict(X_test)
loss=mean_squared_error(y_test,y_pred)
r2=reg_lasso.score(X_test,y_test)
print(f"loss:{loss},R2:{r2}")

print(f"coefficients:{reg_lasso.coef_}")

loss:3787.87429491264,R2:0.26132445466089016
coefficients:[  0.          -0.         409.68653825   0.           0.
   0.          -0.           0.         336.9591004    0.        ]
